### PR TITLE
check for /usr/bin/dot 

### PR DESCRIPTION
**Pull request by ryazwinski**
well check for 'dot' in your search path actually... print a warning if not found.

### CODE REVIEW

**Comment by lmacken** [comment]
Can you do a `git pull --rebase` and re-submit this pull request? For some reason it won't let me automatically merge this one. Thanks!

**Comment by ryazwinski** [comment]
hrm... my branch says it's up to date and the rebase won't work... how
odd...  I pushed again, try the pull?

On Sat, Mar 17, 2012 at 1:48 PM, Luke Macken
reply@reply.github.com
wrote:

> Can you do a `git pull --rebase` and re-submit this pull request? For some reason it won't let me automatically merge this one. Thanks!
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lmacken/pyrasite-gui/pull/3#issuecomment-4555708

## 

## 

http://about.me/ryazwinski

**Comment by lmacken** [comment]
Hmm, now it will auto-merge a bunch of gui changes as well.

Can you try pushing committing each of these into seperate branches and then doing pull requests for each?

I'd like to keep the master branch the latest stable, and work being merged into 'develop'. I'm a big fan of git-flow, and you can easily use it to create new feature/bugfix/release branchs (git flow feature start <name>; git flow feature finish <name>). However, feature finish will merge it back into develop -- I'm thinking it would be best to push the branches out and doing pull requests from them, then I can finish/merge them and spin releases. https://github.com/nvie/gitflow

**Comment by ryazwinski** [comment]
My gtk branch has the dependency checking in it as well
I could push that branch to my git account... does that work?

On Sat, Mar 17, 2012 at 8:19 PM, Luke Macken
reply@reply.github.com
wrote:

> Hmm, now it will auto-merge a bunch of gui changes as well.
> 
> Can you try pushing committing each of these into seperate branches and then doing pull requests for each?
> 
> I'd like to keep the master branch the latest stable, and work being merged into 'develop'. I'm a big fan of git-flow, and you can easily use it to create new feature/bugfix/release branchs (git flow feature start <name>; git flow feature finish <name>). However, feature finish will merge it back into develop -- I'm thinking it would be best to push the branches out and doing pull requests from them, then I can finish/merge them and spin releases. https://github.com/nvie/gitflow
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lmacken/pyrasite-gui/pull/3#issuecomment-4558290

## 

## 

http://about.me/ryazwinski

**Comment by lmacken** [comment]
I have not actually attempted to do that flow yet, so if it becomes a PITA, I can merge this as-is.

**Comment by ryazwinski** [comment]
I've never used git flow... but just sent you my git branch pulll

On Sat, Mar 17, 2012 at 8:25 PM, Luke Macken
reply@reply.github.com
wrote:

> I have actually attempted to do that flow yet, so if it becomes a PITA, I can merge this as-is.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/lmacken/pyrasite-gui/pull/3#issuecomment-4558325

## 

## 

http://about.me/ryazwinski

**Comment by lmacken** [comment]
Merged into the develop branch

**Pull request closed without merging**
